# Stage 1: Build the application
FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Create a minimal runtime image
FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/new-0.0.1-SNAPSHOT.jar new.jar
EXPOSE 9191
ENTRYPOINT ["java", "-jar", "new.jar"]
